toc-title-document: "Tabla de contenidos"
toc-title-website: "En esta página"

related-formats-title: "Otros formatos"
related-notebooks-title: "Cuadernos"
source-notebooks-prefix: "Fuente"
other-links-title: "Otros enlaces"
code-links-title: "Enlaces a código"
launch-dev-container-title: "Launch Dev Container"
launch-binder-title: "Launch Binder"

article-notebook-label: "Cuaderno del artículo"
notebook-preview-download: "Descargar cuaderno"
notebook-preview-download-src: "Download Source"
notebook-preview-back: "Volver al artículo"
manuscript-meca-bundle: "MECA Bundle"

section-title-abstract: "Resumen"
section-title-appendices: "Apéndices"
section-title-footnotes: "Notas al pie"
section-title-references: "Referencias"
section-title-reuse: "Reutilización"
section-title-copyright: "Copyright"
section-title-citation: "Citación"

appendix-attribution-cite-as: "Para Atribución, le agradecemos que cite el trabajo como:"
appendix-attribution-bibtex: "Citación BibTeX:"

title-block-author-single: "Autor"
title-block-author-plural: "Autores"
title-block-affiliation-single: "Afiliación"
title-block-affiliation-plural: "Afiliaciones"
title-block-published: "Publicado"
title-block-modified: "Modificado"
title-block-keywords: "Palabras clave"

callout-tip-title: "Tip"
callout-note-title: "Note"
callout-warning-title: "Warning"
callout-important-title: "Important"
callout-caution-title: "Caution"

code-summary: "Code"

code-tools-menu-caption: "Code"
code-tools-show-all-code: "Show All Code"
code-tools-hide-all-code: "Hide All Code"
code-tools-view-source: "View Source"
code-tools-source-code: "Source Code"

code-line: "Line"
code-lines: "Lines"

copy-button-tooltip: "Copiar al Portapapeles"
copy-button-tooltip-success: "¡Copiado!"

repo-action-links-edit: "Edit this page"
repo-action-links-source: "View source"
repo-action-links-issue: "Report an issue"

back-to-top: "Back to top"

search-no-results-text: "No results"
search-matching-documents-text: "matching documents"
search-copy-link-title: "Copy link to search"
search-hide-matches-text: "Hide additional matches"
search-more-match-text: "more match in this document"
search-more-matches-text: "more matches in this document"
search-clear-button-title: "Clear"
search-detached-cancel-button-title: "Cancel"
search-submit-button-title: "Submit"
search-label: "Search"

toggle-section: "Toggle section"
toggle-sidebar: "Toggle sidebar navigation"
toggle-dark-mode: "Toggle dark mode"
toggle-reader-mode: "Toggle reader mode"
toggle-navigation: "Toggle navigation"

crossref-fig-title: "Figura"
crossref-tbl-title: "Tabla"
crossref-lst-title: "Lista"
crossref-thm-title: "Teorema"
crossref-lem-title: "Lema"
crossref-cor-title: "Corolario"
crossref-prp-title: "Proposición"
crossref-cnj-title: "Conjetura"
crossref-def-title: "Definición"
crossref-exm-title: "Ejemplo"
crossref-exr-title: "Ejercicio"
crossref-ch-prefix: "Capítulor"
crossref-apx-prefix: "Apéndice"
crossref-sec-prefix: "Sección"
crossref-eq-prefix: "Ecuación"
crossref-lof-title: "Lista de figuras"
crossref-lot-title: "Lista de tablas"
crossref-lol-title: "Lista de listas"

environment-proof-title: "Proof"
environment-remark-title: "Remark"
environment-solution-title: "Solution"

listing-page-order-by: "Order By"
listing-page-order-by-default: "Default"
listing-page-order-by-date-asc: "Oldest"
listing-page-order-by-date-desc: "Newest"
listing-page-order-by-number-desc: "High to Low"
listing-page-order-by-number-asc: "Low to High"
listing-page-field-date: "Fecha"
listing-page-field-title: "Título"
listing-page-field-description: "Descripción"
listing-page-field-author: "Autor"
listing-page-field-filename: "Nombre de fichero"
listing-page-field-filemodified: "Modificado"
listing-page-field-subtitle: "Subtítulo"
listing-page-field-readingtime: "Tiempo de lectura"
listing-page-field-wordcount: "Conteo de palabras"
listing-page-field-categories: "Categorias"
listing-page-minutes-compact: "{0} min"
listing-page-category-all: "Todas"
listing-page-no-matches: "No matching items"
listing-page-words: "{0} palabras"
